import { ROLES } from './constants'

const permissions = {
  [ROLES.ADMIN]: {
    canManageUsers: true,
    canManagePosts: true,
    canViewCandidates: true,
    canManageCandidates: true,
    canManageApplications: true,
    canCreateApplication: true,
    canEditApplication: true,
    canViewStats: true,
    canArchivePosts: true,
    canChangeFinalStatus: true,
    canSchedulePhoneInterview: true,
    canScheduleHRInterview: true,
    canScheduleTechnicalInterview: true,
    canScheduleBusinessInterview: true,
    canScheduleFinalInterview: true,
    canScheduleRecruitmentCommittee: true,
    canViewAllInterviews: true,
    canCreateInterview: true,
    canEditInterview: true,
    canCancelInterview: true,
    canDeleteInterview: true,
    canViewAllReports: true,
    canAddInterviewReport: true,
    canEditInterviewReport: true,
    canEditAnyInterviewReport: true,
    canViewInterviewReport: true,
    canDeleteInterviewReport: true,
    canExportInterviewReport: true,
    canValidateInterviewReport: false,
    canValidateOfferAfterReport: false,
  },
  [ROLES.ASSISTANT]: {
    canManageUsers: false,
    canManagePosts: true,
    canViewCandidates: true,
    canManageCandidates: true,
    canManageApplications: true,
    canCreateApplication: true,
    canEditApplication: true,
    canViewStats: false,
    canArchivePosts: false,
    canChangeFinalStatus: false,
    canSchedulePhoneInterview: true,
    canScheduleHRInterview: true,
    canScheduleTechnicalInterview: true,
    canScheduleBusinessInterview: true,
    canScheduleFinalInterview: false,
    canScheduleRecruitmentCommittee: false,
    canViewAllInterviews: true,
    canCreateInterview: true,
    canEditInterview: true,
    canCancelInterview: true,
    canDeleteInterview: false,
    canViewAllReports: true,
    canAddInterviewReport: true,
    canEditInterviewReport: true,
    canEditAnyInterviewReport: true,
    canViewInterviewReport: true,
    canDeleteInterviewReport: false,
    canExportInterviewReport: true,
    canValidateInterviewReport: false,
    canValidateOfferAfterReport: false,
  },
  [ROLES.MANAGER]: {
    canManageUsers: false,
    canManagePosts: false,
    canViewCandidates: true,
    canManageCandidates: false,
    canManageApplications: true,
    canCreateApplication: false,
    canEditApplication: false,
    canViewStats: false,
    canArchivePosts: false,
    canChangeFinalStatus: true,
    canSchedulePhoneInterview: false,
    canScheduleHRInterview: false,
    canScheduleTechnicalInterview: true,
    canScheduleBusinessInterview: true,
    canScheduleFinalInterview: false,
    canScheduleRecruitmentCommittee: false,
    canViewAllInterviews: false,
    canCreateInterview: false,
    canEditInterview: false,
    canCancelInterview: false,
    canDeleteInterview: false,
    canViewAllReports: false,
    canAddInterviewReport: true,
    canEditInterviewReport: true,
    canEditAnyInterviewReport: false,
    canViewInterviewReport: true,
    canDeleteInterviewReport: false,
    canExportInterviewReport: true,
    canValidateInterviewReport: false,
    canValidateOfferAfterReport: false,
  },
  [ROLES.DIRECTION]: {
    canManageUsers: false,
    canManagePosts: false,
    canViewCandidates: false,
    canManageCandidates: false,
    canManageApplications: true,
    canCreateApplication: false,
    canEditApplication: false,
    canViewStats: true,
    canArchivePosts: false,
    canChangeFinalStatus: true,
    canSchedulePhoneInterview: false,
    canScheduleHRInterview: false,
    canScheduleTechnicalInterview: false,
    canScheduleBusinessInterview: false,
    canScheduleFinalInterview: false,
    canScheduleRecruitmentCommittee: false,
    canViewAllInterviews: true,
    canCreateInterview: false,
    canEditInterview: false,
    canCancelInterview: false,
    canDeleteInterview: false,
    canViewAllReports: true,
    canAddInterviewReport: false,
    canEditInterviewReport: false,
    canEditAnyInterviewReport: false,
    canViewInterviewReport: true,
    canDeleteInterviewReport: false,
    canExportInterviewReport: true,
    canValidateInterviewReport: true,
    canValidateOfferAfterReport: true,
  },
}

export const getRolePermissions = (roleName) => permissions[roleName] || {}

export const hasPermission = (roleName, permissionKey) => {
  const rolePermissions = getRolePermissions(roleName)
  return Boolean(rolePermissions[permissionKey])
}
